### ISSUE TITLE
Custom User Model

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#18]
This is needed to provide things like roles, permissions, etc

- [x] name (provided by django/wagtail)
- [x] email (provided by django/wagtail)
- [x] role (provided by django/wagtail)
  - author
  - coach
  - translator
- [ ] job title

[Wagtail docs for customizing user model](http://docs.wagtail.io/en/v1.13.1/advanced_topics/customisation/custom_user_models.html)

**Comment by jessereitz** [comment]
@benweatherman Are y'all just looking for that job title field added or is there other specific fields that should be added?

**Comment by benweatherman** [comment]
Thanks for asking! We're waiting on feedback to see if the field is necessary or if we can pull it from an internal system at the city.
