### ISSUE TITLE
Better input mechanism for Hours of Operation

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#27]
Currently it looks like
<img width="976" alt="hour input" src="https://user-images.githubusercontent.com/272675/34058268-0008dea8-e1a0-11e7-8bba-fe351f8f8254.png">

It's not ideal because
- It takes up a lot of vertical space
- Easy to forget a day of the week

There are lots of [good ideas on stackoverflow](https://ux.stackexchange.com/questions/33600/form-for-inputting-operating-hours-of-a-business). There's also some [UX design guidelines](https://www.nngroup.com/articles/date-input/) put out by big brained designers.

**Comment by ifsimicoded** [comment]
Also worth considering how 'closed' is handled

**Comment by benweatherman** [comment]
I like this solution from the SO link because it would be easy to assume unchecked dates are closed or we could show closed in the UI if the day is unchecked

![image](https://user-images.githubusercontent.com/272675/34388242-2c18d208-eaf8-11e7-96d0-d7fc64f93780.png)

I'm not sure the best way to represent that via the API
- Don't return the day of week if it's closed
- Return `start_time=end_time=null`
- Your Suggestion Here
