### ISSUE TITLE
Live preview for mobile

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#32]

**Comment by benweatherman** [comment]
This is mostly working. We should probably start talking design tweaks.

![live-preview](https://user-images.githubusercontent.com/272675/34596754-ddec00c6-f1a7-11e7-9e99-b60de8ade744.gif)

**Comment by benweatherman** [comment]
I'm going to call this good enough for a first pass. We can file more specific issues as they come up.

**Comment by mateoclarke** [comment]
@toribr, just a heads up that we're closing out this first iteration on Mobile Preview in the Joplin UX. As you prioritize design in the CMS, maybe keep improvements here in mind?
