### ISSUE TITLE
Add feedback when field has changed for preview

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#35]
When an author starts changing a field, we should provide feedback in the preview window that things are gonna change (e.g. a spinner). We should also provide feedback when the page is done rendering (e.g. hide a spinner).

**Comment by cthibaultatx** [comment]
@benweatherman want me to mock something up for this?

**Comment by benweatherman** [comment]
Would it be alright to walk through the preview first? I think there are other things we'll want to change also.
