### ISSUE TITLE
Department Model and Dept Page endpoint

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/joplin#36]
Related to page required in Joplin and issue https://github.com/cityofaustin/janis/issues/34

Needs:
- Title
- Mission
- Image
- Projects (new Model)
- Multiple Contacts -> Email, Phone, Address, Hours

**Comment by benweatherman** [comment]
Projects isn't included yet because I'm not sure how authors will enter those things. Will add once we figure that out.

![department graphql](https://user-images.githubusercontent.com/272675/34742136-c97977f8-f54a-11e7-9dcf-879683b4f212.png)

**Comment by benweatherman** [comment]
This was used in making a department page, so I'm calling it good enough for now
