### ISSUE TITLE
Topic Model and Page Endpoint

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/joplin#37]
Currently we have an endpoint that gives us all services.
Similarly we need an endpoint that will give us all services for a topic.
Needs
- topic name
- topic text
- topic image
- list of services for that topic

Related to issue: https://github.com/cityofaustin/janis/issues/29

**Comment by benweatherman** [comment]
See changes referenced in this issue for how to use. Let me know if there are any other tweaks to make.

**Comment by ifsimicoded** [comment]
Hey @benweatherman 
Can I get you to add a slug field for topics so we can have pretty urls for topic pages.
And, the description field we currently have may need to be limited WYSIWYG field type.

**Comment by benweatherman** [comment]
Added cityofaustin/joplin#58 for URLs. I agree about the WYSIWYG field, but I'll hold off until we hear feedback from authors.
