### ISSUE TITLE
Service Page Endpoint updates

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/joplin#38]
Return related services when a service page is requested.
Append the Service Page data with an array of abbreviated service models (id, title, slug) for all services with the same topic.

We'll eventually modify the logic for which related services gets returned, but with our limited set of services, this will work for now.

**Comment by benweatherman** [comment]
See changes referenced from this issue for how to use it

Here's an example of it working in the UI

![related](https://user-images.githubusercontent.com/272675/34629486-e790e94e-f22d-11e7-853f-0352477312d2.gif)
