### ISSUE TITLE
Author "Manage Content" Dashboard

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#4]
![awesome-cms_admin_dash_20170102](https://user-images.githubusercontent.com/20911665/34503365-7f399c30-efdd-11e7-9af6-451860505a21.png)

Dashboard enables content creators to:
- navigate quickly to specific pieces of content
- review actionable KPIs on all content (ex. KPI is mobile traffic)
- keep content up to date
- run reports on content (can be a separate feature)

- [ ] Need to design user flow for content admins

- [ ] Need to design user flow for content coaches

**Comment by mateoclarke** [comment]
Stumbled on this today: https://github.com/tomdyson/wagalytics
