### ISSUE TITLE
Automate returning related services

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#53]
Currently, the joplin API returns all services for a topic when returning related services

https://github.com/cityofaustin/joplin/blob/1f7b9b8947612db66c87a00f2403f929a806369d/joplin/api/schema.py#L69

This should be smarter

**Comment by cthibaultatx** [comment]
@benweatherman I believe we're beginning with 6 services under 1 topic category. I imagine the way it works now is a service page returns all other services related by topic OR it returns 3 of the other services related by topic. Ideally, the services are filtered before returning so residents are not seeing a list of 5 related services OR seeing the same set of 3 on each page.
