### ISSUE TITLE
Analytics for CMS

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/joplin#56]
We should add analytics to the CMS so we can see how authors are using the system.

- How often is content updated per day?
- How many users log in each day?

**Comment by mateoclarke** [comment]
@laconc suggested we check out https://github.com/snowplow/snowplow-javascript-tracker
- saves event stream data to S3 or another source. store the data now and push the data into a managed service like mixedpanel later.
- may drop ~10% of users if they have adblockers or other anti-tracking software

**Comment by laconc** [comment]
Correction on my last statement: since Mixpanel has their own event trackers, I can't imagine that they would import data easily from other sources. With that said, there are many other tools to analyze your data, including a lot of open source ones.

**Comment by benweatherman** [comment]
Thanks for the suggestion @laconc!
