### ISSUE TITLE
Bad link to local path

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/joplin#7]
Once the local server spins up, the docker command tells you:

```
Django version 1.11.7, using settings 'settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
```
But the path to the server is actually http://localhost:8000/.

Should we update the way this prints in the server logs? I tried editing this line, but it didnt work:
https://github.com/cityofaustin/joplin/blame/master/Dockerfile#L15-L16

**Comment by benweatherman** [comment]
Hmmm, this is an interesting one. Inside the docker container it's using port 80. But we map localhost:8000 to docker port 80 so we don't have to use port 80 on our dev computer.
