### ISSUE TITLE
Debo does not feel well

### ISSUE THREAD

**Issue by MireyaGalarza** [cityofaustin/joplin#79]
Where is the template?

**Comment by juliazbyron** [comment]
You are obsessed with Debo! I hope he's not actually sick though

**Comment by MireyaGalarza** [comment]
@juliazbyron -He is so cute!   he ate something funny.  He is better.  
![my favorite pet](https://user-images.githubusercontent.com/3902994/35360823-a2875936-0124-11e8-8226-9c2cb94b430d.jpeg)
